### ISSUE TITLE
錯誤報告

### ISSUE THREAD

**Issue by jasper9608** [QuasiMkl/mckismetlab-launcher#1]
**描述錯誤**
清楚簡單描述你遇到了什麼錯誤?
模主包無法開啟
**出錯步驟**
請列出你出錯的步驟:
1. 點擊 '....'開始遊戲
2. 你看到什麼錯誤遊戲崩潰
3. .......
4. .....

**螢幕截圖**
如果可以，請添加截圖我們會比較清楚你發生問題。
![螢幕擷取畫面 2021-06-13 163400](https://user-images.githubusercontent.com/85822666/121800561-3f423980-cc65-11eb-9bc4-1d53a99bc271.png)

**電腦規格 (請填寫以下信息):**
 - 作業系統(Windows 、 Linux 、 Mac):
Windows
**其他錯誤內容**
如果可以，在此處添加有關該錯誤報告問題。

**Comment by yucheng918** [comment]
有嘗試使用修復功能嗎?

![螢幕擷取畫面 2021-06-14 080844](https://user-images.githubusercontent.com/48871339/121825943-bfa97e80-cce7-11eb-8889-ab1063afd3d1.png)
