### ISSUE TITLE
錯誤報告

### ISSUE THREAD

**Issue by liang36176381** [QuasiMkl/mckismetlab-launcher#3]
**描述錯誤**
每次重開會自動把設定調回預設

**出錯步驟**
請列出你出錯的步驟:
1. 點擊 '開始遊戲'
2. 更改遊戲設定 ex.顯示, 按鍵
3. 關閉遊戲
4. 重新使用無名啟動器開啟遊戲
5. 進入遊戲設定，設定被調回預設

**電腦規格 (請填寫以下信息):**
 - 作業系統:Windows

**Comment by yucheng918** [comment]
下個版本中修復
