### ISSUE TITLE
無法使用mojang

### ISSUE THREAD

**Issue by myes107002** [QuasiMkl/mckismetlab-launcher#4]
**請清楚的描述你想要功能**
我沒有辦法使用mojang帳號只能使用microsoft的帳號因為我把mojang的帳號遷移到了microsoft裡
我希望你能讓我使用microsoft的帳號加入您的伺服器
![image](https://user-images.githubusercontent.com/91774727/135706436-a2ab1ea3-400f-4ab6-bf00-ad0e443122c8.png)
我用的密碼是********

**Comment by yucheng918** [comment]
已在計畫中，下個版本中新增支援微軟登入
