### ISSUE TITLE
is there an english language option in the launcher?

### ISSUE THREAD

**Issue by JEijiandrei** [QuasiMkl/mckismetlab-launcher#5]

**Comment by yucheng918** [comment]
no english option :(

**Comment by JEijiandrei** [comment]
can u pls add english option if its ok to you

**Comment by ghost** [comment]
I'll help add an English option. However, @QuasiMkl, you'll need to add a language setting.
I guess it'll be JSON files that I need to make.

**Comment by yucheng918** [comment]
> I'll help add an English option. However, @QuasiMkl, you'll need to add a language setting. I guess it'll be JSON files that I need to make.

Thank you !

**Comment by ghost** [comment]
Translated: #9

**Comment by ghost** [comment]
This issue can now be closed.

**Comment by QuasiMkl** [comment]
The launcher now supports English language, I will close issue.

**Comment by yucheng918** [comment]
The launcher now supports English language, I will close issue.
