### ISSUE TITLE
官方啟動器mac版本？

### ISSUE THREAD

**Issue by yc815-mc** [QuasiMkl/mckismetlab-launcher#6]
我是mac的用戶，我想要玩你們的伺服器，請問有mac版本的官方啟動器下載點嗎？謝謝，辛苦了！

**Comment by yucheng918** [comment]
目前沒有為 mac 版本支援，不過我現在已經在開發新的UI啟動器也會同步支持 mac 版本，需要時間完成。感謝你的支持！

**Comment by yc815-mc** [comment]
好的！謝謝回答！
有開放測試或著軟體製作完成時，麻煩提示一下！
謝謝！

**Comment by yucheng918** [comment]
啟動器現在支持 mac x64 版本 [v0.4.0-beta](https://github.com/mcKismetLab/mckismetlab-launcher/releases/tag/v0.4.0-beta)，我將關閉問題。
