### ISSUE TITLE
回報錯誤

### ISSUE THREAD

**Issue by litchi1006** [QuasiMkl/mckismetlab-launcher#8]
**描述錯誤**
清楚簡單描述你遇到了什麼錯誤?
下載進度條卡在75%
**出錯步驟**
請列出你出錯的步驟:
1. 點擊 '開始遊戲'
2. 我看到進度條
3. 30分鐘還在75%
4. .....

**螢幕截圖**
如果可以，請添加截圖我們會比較清楚你發生問題。

**電腦規格 (請填寫以下信息):**
 - 作業系統(Windows 、 Linux 、 Mac):

**其他錯誤內容**
如果可以，在此處添加有關該錯誤報告問題。

**Comment by yucheng918** [comment]
試試看使用內建修復功能 #1
